name: "PR Title Validation"

on:
  workflow_call:
    inputs:
      conventional-commit-types:
        description: "Newline-separated list of allowed conventional commit types"
        required: false
        type: string
        default: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
      conventional-commit-scopes:
        description: "Newline-separated list of allowed scopes (empty = any scope allowed)"
        required: false
        type: string
        default: ""
      runs-on:
        description: "Runner label"
        required: false
        type: string
        default: "ubuntu-latest"
    secrets:
      github-token:
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-validation:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: "Validate PR"
        uses: braintree/web-sdk-github-actions/actions/validate-pr@main
        with:
          github-token: ${{ secrets.github-token }}
          conventional-commit-types: ${{ inputs.conventional-commit-types }}
          conventional-commit-scopes: ${{ inputs.conventional-commit-scopes }}
